### ISSUE TITLE
切换wind配色会导致文档图标变灰且透明，再切换到其他配色改样式依旧存在

### ISSUE THREAD

**Issue by muhanstudio** [royc01/Odyssey#1]
![image](https://github.com/royc01/Odyssey/assets/29907393/0e6f78ef-eb1a-4c53-9d43-26f5bc5a56f3)
![image](https://github.com/royc01/Odyssey/assets/29907393/b0830e01-b87e-48a4-9160-39fb434c6ea1)
如图看起来有一点怪怪的

**Comment by royc01** [comment]
收到，下个版本修复
