### ISSUE TITLE
框选到标题块时出错

### ISSUE THREAD

**Issue by onemonet** [royc01/Odyssey#11]
当从下向上框选时候，框选到标题上一个块的下边缘时，会错误选择上方所有的块
1. 未开启代码片段
2. 官方主题没有复现
![PixPin_2024-09-03_16-35-53](https://github.com/user-attachments/assets/f53662c2-b2cc-42d5-87b5-06c0b7d96b07)

**Comment by royc01** [comment]
感谢反馈 v1.1.8修复
