### ISSUE TITLE
垂直页签存在的问题

### ISSUE THREAD

**Issue by cordinGH** [royc01/Odyssey#15]
垂直页签非常非常好用，但就是分屏时 每个屏都会开启垂直页签，导致占用了一些不必要的视觉空间。

场景：主屏写笔记，然后 `alt+B` 打开了某个页面的反链，同时 `ctrl+shift+f` 打开固定搜索，然后页面就成了这样
![image](https://github.com/user-attachments/assets/74e20d7c-7b97-4dbc-ac53-5b0a209dbd15)
**不难看出，这里的反链屏还有搜索屏，其实并不需要垂直页签，否则会占用很多显示空间。**

所以，如果能为「垂直页签」增加一个二级选项就好了~~
![image](https://github.com/user-attachments/assets/3852edcd-0b65-4405-94a0-77fd12123c81)
（`第一屏` 这个用词可能不准确，或者用`主屏`？）

**Comment by royc01** [comment]
v2.0.0重构版本会有优化，等上线后下载测试下

**Comment by cordinGH** [comment]
有重启，还是没用，然后也尝试了卸载主题重新安装

**Comment by royc01** [comment]
我找找问题

**Comment by cordinGH** [comment]
遇上了奇奇怪怪的bug，有点懵逼现在，我刚下载了1.1.19版本，然后启用后，任我行的功能切换菜单 会被编辑器遮盖，然后垂直页签样式也回不去1.1.19版本
尝试过重启思源，以及只保留1.1.19的主题文件夹

**Comment by royc01** [comment]
以前的版本是比较多问题，插件消失可能是你用了合并顶栏插件折叠功能，我下个版本取消下

**Comment by cordinGH** [comment]
> 以前的版本是比较多问题，插件消失可能是你用了合并顶栏插件折叠功能，我下个版本取消下

@royc01 
感觉不是上个版本的问题。
我刚才把下载解压的Odyssey-1.1.19文件夹名，重命名为“Odyssey”后，再复制进themes，就成功回退了。

**Comment by royc01** [comment]
好的，新版重构没有经过大量测试会比较多问题，多担待

**Comment by cordinGH** [comment]
> 好的，新版重构没有经过大量测试会比较多问题，多担待

理解！r大幸苦了。

我想了一下，可能是思源手动导入存在问题，而不是主题自身所致。因为自从我刚才重命名再导入后，就什么问题都没了，包括一开始提到的2.0顶栏按钮的问题。

**Comment by cordinGH** [comment]
因为一开始集市没有显示更新按钮，我就去github直接下载了，然后解压后直接复制了进去（没有重命名移除掉尾部的“-2.0.0”）

**Comment by cordinGH** [comment]
r大有没有计划单独发布一个只升级垂直页签的1.1.19版本（期待.jpg）

**Comment by royc01** [comment]
这个应该不做优化了，做这个实在是耗费时间所以才统一修改，一劳永逸

**Comment by cordinGH** [comment]
> 这个应该不做优化了，做这个实在是耗费时间所以才统一修改，一劳永逸

也是，尊重r大。
只能以后尝试自行修改了，因为相较而言还是觉得任我行主题更好看。
