### ISSUE TITLE
标签显示异常

### ISSUE THREAD

**Issue by 50Hz-debug** [royc01/Odyssey#2]
![12D6BAF5B0BEF733ED6B0A2526E13A9F](https://github.com/royc01/Odyssey/assets/78454737/f60dae33-fba2-4242-8022-a9143b3fdbfe)
同情况下savor
![1705133364375](https://github.com/royc01/Odyssey/assets/78454737/f568cb77-d649-47b8-9b2c-5feb56ab8670)

**Comment by royc01** [comment]
感谢反馈，v1.1.3修复
