### ISSUE TITLE
段落块在写入内容后无法点击打开快捷列表

### ISSUE THREAD

**Issue by rumengsiji** [royc01/Odyssey#3]
![image](https://github.com/royc01/Odyssey/assets/63029384/0096237e-ea17-4208-bd0d-4050484b1a2f)
点这里时
![image](https://github.com/royc01/Odyssey/assets/63029384/c685561f-4617-438b-9165-706b19244249)
不能出现这个列表

**Comment by royc01** [comment]
你好，我这边是正常的，或者打开开发者工具看看有没有报错
