### ISSUE TITLE
收集箱点击文章后缺少返回箭头

### ISSUE THREAD

**Issue by mozhux** [royc01/Odyssey#4]
如题
![image](https://github.com/mustakshif/Asri/assets/46953371/7f7bb46f-93bd-4668-b636-2e4a12ffc5f5)
![image](https://github.com/royc01/Odyssey/assets/46953371/5b41c44a-5e32-4cc0-aad8-7b4c4b947293)

**Comment by royc01** [comment]
感谢反馈，v1.1.3修复
